# Generated by Django 3.2.1 on 2021-06-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='category',
            field=models.CharField(choices=[('중고 기계', '중고 기계'), ('신품 기계', '신품 기계')], default='', max_length=20),
        ),
    ]
