# Generated by Django 3.2.1 on 2021-06-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_alter_machine_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
