# Generated by Django 3.2.1 on 2021-05-18 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_machine_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='pick',
        ),
    ]
